ARENA_ROWS = 7
ARENA_COLUMNS = 7
KNIGHT_R_INITIAL_ROW = 0
KNIGHT_R_INITIAL_COL = 0
KNIGHT_G_INITIAL_ROW = 7
KNIGHT_G_INITIAL_COL = 7
KNIGHT_Y_INITIAL_ROW = 0
KNIGHT_Y_INITIAL_COL = 7
KNIGHT_B_INITIAL_ROW = 7
KNIGHT_B_INITIAL_COL = 0

ITEM_AXE_INITIAL_ROW = 2
ITEM_AXE_INITIAL_COL = 2
ITEM_AXE_PRIOROTY = 4
ITEM_AXE_ATTACK = 2
ITEM_AXE_DEFENCE = 0

ITEM_MAGIC_STAFF_INITIAL_ROW = 5
ITEM_MAGIC_STAFF_INITIAL_COL = 2
ITEM_MAGIC_STAFF_PRIOROTY = 3
ITEM_MAGIC_STAFF_ATTACK = 1
ITEM_MAGIC_STAFF_DEFENCE = 1

ITEM_DAGGER_INITIAL_ROW = 2
ITEM_DAGGER_INITIAL_COL = 5
ITEM_DAGGER_PRIOROTY = 2
ITEM_DAGGER_ATTACK = 1
ITEM_DAGGER_DEFENCE = 0

ITEM_HELMET_INITIAL_ROW = 5
ITEM_HELMET_INITIAL_COL = 5
ITEM_HELMET_PRIOROTY = 1
ITEM_HELMET_ATTACK = 0
ITEM_HELMET_DEFENCE = 1

MOVEMENTS_FILENAME = "./moves.txt"
TEST_FILE = "./test_results.json"